name: Deprecation/Undeprecation
description: Request to deprecate or undeprecate a package
title: "[Un/Deprecation] "
body:
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Reason for deprecation or undeprecation
    validation:
      required: true

  - type: checkboxes
    id: depends-on
    attributes:
      label: Does this request depend on package changes to land first?
      description: This request depends on a package change to land before this can be merged.
      options:
        - label: Yes

  - type: input
    id: diff-url
    attributes:
      label: Package Diff
      description: The URL to the package change this depends on, if any
      placeholder: https://dev.getsol.us/D00000
