name: Other
description: Any other code change
title: ""
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Details about what this Pull Request does
      placeholder: This pull request does...
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Submitter Checklist
      description: Check all that apply
      options:
        - label: "Squashed commits with `git rebase -i` (if needed)"
        - label: Built solus-sc and verified that the patch worked (if needed)
